keymap:
    red:
        index: 5
        pad: ACOUSTIC_SNARE
    blue:
        index: 7
        pad: HIGH_FLOOR_TOM
    green:
        index: 4
        pad: LOW_MID_TOM
    yellow:
        index: 6 
        pad: OPEN_HI_HAT 
    orange:
        index: 8
        pad: CRASH_CYMBAL_1
    purple:
        index: 9
        pad: BASS_DRUM_1
    # plus:
        # index: ?
        # pad: HAND_CLAP
    # minus:
        # index: ?
        # pad: COWBELL

midimap:
    BASS_DRUM_1: 36
    SIDE_STICK: 37 
    ACOUSTIC_SNARE: 38
    HAND_CLAP: 39
    ELECTRIC_SNARE: 40
    LOW_FLOOR_TOM: 41
    CLOSED_HI_HAT: 42
    MID_FLOOR_TOM: 43
    PEDAL_HI_HAT: 44
    HIGH_FLOOR_TOM: 45
    OPEN_HI_HAT: 46
    LOW_MID_TOM: 47
    HI_MID_TOM: 48
    CRASH_CYMBAL_1: 49
    HIGH_TOM: 50
    RIDE_CYMBAL_1: 51
    FLAT_SNARE: 52
    BASS_DRUM_2: 53

    # NOT ALWAYS PRESENT
    SPLASH_CYMBAL: 54
    COWBELL: 55
    TAMBOURINE: 56
    VIBRASLAP: 57
    ANYTHING: 58
    VIBRASLAP_2: 59
